### ISSUE TITLE
Problem trying to use Shortcode in Laravel 5

### ISSUE THREAD

**Issue by grafikkaos** [pingpong-labs/shortcode#5]
Trying to use the shortcode package in an app I am working on but I am getting this error:

ErrorException in AliasLoader.php line 63:
Class 'Pingpong\Shortcode\Facades\Shortcode' not found

I do have the required provider and facade lines in the app.php file, so could it be that Shortcode is not ready for laravel 5?

thanks

**Comment by grafikkaos** [comment]
I should mention I am using the 2.0.*@dev branch

**Comment by gravitano** [comment]
Hi,

Use `Pingpong\Shortcode\ShortcodeFacade` class instead. I haven't updated the documentation.
